language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer update
  - mysql -e 'CREATE DATABASE uFlex_UT;'
  - mysql uFlex_UT < db/users_table.sql'

script: phpunit -c tests/phpunit.xml.dist